from typing import TypedDict
from langchain_core.documents import Document


class GraphState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    """

    # User's original or rewritten question
    question: str

    # Documents retrieved from ChromaDB
    retrieved_docs: list[Document]

    # Documents that passed the grading step
    relevant_docs: list[Document]

    # Final answer generated by the LLM
    answer: str

    # Number of times the query has been rewritten/retried
    retry_count: int